name: CD/CI

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Backend Build, Test, and Push to GHCR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      working-directory: ./backend
      run: |
        make install

    - name: Lint with pylint
      working-directory: ./backend
      run: |
        make lint

    - name: Test with pytest
      working-directory: ./backend
      run: |
        make test

    - name: Log in to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Docker Image
      working-directory: ./backend
      run: |
        docker build -t ghcr.io/${{ github.repository_owner | toLower }}/backend:latest .
        docker push ghcr.io/${{ github.repository_owner | toLower }}/backend:latest

  frontend:
    name: Frontend Build, Test, and Push to GHCR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      working-directory: ./frontend
      run: |
        make install

    - name: Lint frontend code
      working-directory: ./frontend
      run: |
        make lint

    - name: Test frontend
      working-directory: ./frontend
      run: |
        make test

    - name: Log in to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and Push Docker Image
      working-directory: ./frontend
      run: |
        docker build -t ghcr.io/${{ github.repository_owner | toLower }}/frontend:latest .
        docker push ghcr.io/${{ github.repository_owner | toLower }}/frontend:latest